# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import tone_service_pb2 as tone__service__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tone_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ToneServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTone = channel.unary_unary(
                '/ToneService/GetTone',
                request_serializer=tone__service__pb2.GetToneRequest.SerializeToString,
                response_deserializer=tone__service__pb2.GetToneResponse.FromString,
                _registered_method=True)


class ToneServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTone(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ToneServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTone': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTone,
                    request_deserializer=tone__service__pb2.GetToneRequest.FromString,
                    response_serializer=tone__service__pb2.GetToneResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ToneService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ToneService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ToneService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ToneService/GetTone',
            tone__service__pb2.GetToneRequest.SerializeToString,
            tone__service__pb2.GetToneResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
