# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tone_service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'tone_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12tone_service.proto\x12\x04tone\"\x1e\n\x0eGetToneRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"+\n\x0fGetToneResponse\x12\x18\n\x04tone\x18\x01 \x01(\x0e\x32\n.tone.Tone*B\n\x04Tone\x12\x14\n\x10TONE_UNSPECIFIED\x10\x00\x12\x11\n\rTONE_POSITIVE\x10\x01\x12\x11\n\rTONE_NEGATIVE\x10\x02\x32\x45\n\x0bToneService\x12\x36\n\x07GetTone\x12\x14.tone.GetToneRequest\x1a\x15.tone.GetToneResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tone_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TONE']._serialized_start=105
  _globals['_TONE']._serialized_end=171
  _globals['_GETTONEREQUEST']._serialized_start=28
  _globals['_GETTONEREQUEST']._serialized_end=58
  _globals['_GETTONERESPONSE']._serialized_start=60
  _globals['_GETTONERESPONSE']._serialized_end=103
  _globals['_TONESERVICE']._serialized_start=173
  _globals['_TONESERVICE']._serialized_end=242
# @@protoc_insertion_point(module_scope)
