name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest  # AMD64 по умолчанию
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker image
        run: |
          docker build -t mal91r/feedback-service-amd64 .
          docker push mal91r/feedback-service-amd64
